import esbuild from "esbuild";
import fs from "fs";
import process from "process";
import builtins from "builtin-modules";

function copyPdfWorker() {
	if (!prod) return;
	const source = new URL('./node_modules/pdfjs-dist/build/pdf.worker.mjs', import.meta.url);
	fs.copyFileSync(source, new URL('./pdf.worker.mjs', import.meta.url));
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const packageJson = JSON.parse(fs.readFileSync(new URL('./package.json', import.meta.url), 'utf-8'));
const appVersion = packageJson.version;
const releaseCodename = packageJson.releaseCodename ?? 'Reed';
const buildId = `${appVersion}+${new Date().toISOString()}`;

await import('./scripts/sync-styles.mjs');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		__APP_VERSION__: JSON.stringify(appVersion),
		__BUILD_ID__: JSON.stringify(buildId),
		__RELEASE_CODENAME__: JSON.stringify(releaseCodename),
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	copyPdfWorker();
	process.exit(0);
} else {
	await context.watch();
}
